START TRANSACTION;

-- 2. 통합 임시 시드 테이블 생성
DROP TEMPORARY TABLE IF EXISTS `food_ingredient_seed`;

CREATE TEMPORARY TABLE `food_ingredient_seed` (
    `name` VARCHAR(255) NOT NULL,
    `type` VARCHAR(255) NOT NULL,
    `price_per_hundred` INT NOT NULL,
    `primary_unit` VARCHAR(50) NOT NULL,
    `secondary_unit` VARCHAR(50) NOT NULL,
    `allergy` BOOLEAN NOT NULL DEFAULT FALSE,
    `dislike` BOOLEAN NOT NULL DEFAULT FALSE
);

-- 3. 통합 시드 데이터 삽입
INSERT INTO `food_ingredient_seed`
(`name`, `type`, `price_per_hundred`, `primary_unit`, `secondary_unit`, `allergy`, `dislike`)
VALUES
    -- 구근 및 전분류
    ('감자', 'POTATO_AND_STARCH', 550, 'G', 'GAE', FALSE, FALSE),
    ('감자전분', 'POTATO_AND_STARCH', 550, 'G', 'CUP', FALSE, FALSE),
    ('고구마', 'POTATO_AND_STARCH', 550, 'G', 'GAE', FALSE, FALSE),
    ('고구마 전분', 'POTATO_AND_STARCH', 550, 'G', 'CUP', FALSE, FALSE),
    ('곤약', 'POTATO_AND_STARCH', 550, 'G', 'GAE', FALSE, FALSE),
    ('단호박', 'POTATO_AND_STARCH', 550, 'G', 'GAE', FALSE, FALSE),
    ('돼지감자', 'POTATO_AND_STARCH', 550, 'G', 'GAE', FALSE, FALSE),
    ('마', 'POTATO_AND_STARCH', 550, 'G', 'GAE', FALSE, FALSE),
    ('밤', 'POTATO_AND_STARCH', 550, 'G', 'AL', FALSE, FALSE),
    ('쌀 전분', 'POTATO_AND_STARCH', 550, 'G', 'CUP', FALSE, FALSE),
    ('애호박', 'POTATO_AND_STARCH', 550, 'G', 'GAE', FALSE, FALSE),
    ('야콘', 'POTATO_AND_STARCH', 550, 'G', 'GAE', FALSE, FALSE),
    ('옥수수 전분', 'POTATO_AND_STARCH', 550, 'G', 'CUP', FALSE, FALSE),
    ('카사바', 'POTATO_AND_STARCH', 550, 'G', 'GAE', FALSE, FALSE),
    ('타피오카 전분', 'POTATO_AND_STARCH', 550, 'G', 'CUP', FALSE, FALSE),
    ('칡뿌리 전분', 'POTATO_AND_STARCH', 550, 'G', 'CUP', FALSE, FALSE),
    ('토란 전분', 'POTATO_AND_STARCH', 550, 'G', 'CUP', FALSE, FALSE),
    ('호박', 'POTATO_AND_STARCH', 550, 'G', 'GAE', FALSE, FALSE),
    ('분모자', 'POTATO_AND_STARCH', 700, 'G', 'INBUN', FALSE, FALSE),

    -- 견과 및 종실류
    ('도토리', 'NUT_AND_SEED', 2400, 'G', 'AL', FALSE, FALSE),
    ('도토리묵', 'NUT_AND_SEED', 2400, 'G', 'MO', FALSE, FALSE),
    ('들깨', 'NUT_AND_SEED', 2400, 'G', 'TBSP', FALSE, FALSE),
    ('땅콩', 'NUT_AND_SEED', 2400, 'G', 'AL', TRUE, FALSE),
    ('땅콩버터', 'NUT_AND_SEED', 1500, 'G', 'TBSP', TRUE, FALSE),
    ('수박씨', 'NUT_AND_SEED', 2400, 'G', 'AL', FALSE, FALSE),
    ('아몬드', 'NUT_AND_SEED', 2400, 'G', 'AL', FALSE, FALSE),
    ('은행', 'NUT_AND_SEED', 2400, 'G', 'AL', FALSE, TRUE),
    ('잣', 'NUT_AND_SEED', 2400, 'G', 'AL', TRUE, FALSE),
    ('검정깨', 'NUT_AND_SEED', 2400, 'G', 'TBSP', FALSE, FALSE),
    ('참깨', 'NUT_AND_SEED', 2400, 'G', 'TBSP', FALSE, FALSE),
    ('흰깨', 'NUT_AND_SEED', 2400, 'G', 'TBSP', FALSE, FALSE),
    ('코코넛', 'NUT_AND_SEED', 2400, 'G', 'GAE', FALSE, FALSE),
    ('피스타치오', 'NUT_AND_SEED', 2400, 'G', 'AL', FALSE, FALSE),
    ('해바라기씨', 'NUT_AND_SEED', 2400, 'G', 'AL', FALSE, FALSE),
    ('헤이즐넛', 'NUT_AND_SEED', 2400, 'G', 'AL', FALSE, FALSE),
    ('호두', 'NUT_AND_SEED', 2400, 'G', 'AL', TRUE, FALSE),
    ('호박씨', 'NUT_AND_SEED', 2400, 'G', 'AL', FALSE, FALSE),
    ('캐슈넛', 'NUT_AND_SEED', 2400, 'G', 'AL', FALSE, FALSE),
    ('피칸', 'NUT_AND_SEED', 2500, 'G', 'AL', FALSE, FALSE),
    ('마카다미아', 'NUT_AND_SEED', 2800, 'G', 'AL', FALSE, FALSE),

    -- 곡류, 면, 떡, 빵류
    ('귀리 (오트)', 'GRAIN', 450, 'G', 'CUP', FALSE, FALSE),
    ('기장', 'GRAIN', 450, 'G', 'CUP', FALSE, FALSE),
    ('옥수수', 'GRAIN', 450, 'G', 'GAE', FALSE, FALSE),
    ('콘샐러드', 'GRAIN', 450, 'G', 'CUP', FALSE, FALSE),
    ('백미', 'GRAIN', 450, 'G', 'CUP', FALSE, FALSE),
    ('현미', 'GRAIN', 450, 'G', 'CUP', FALSE, FALSE),
    ('흑미', 'GRAIN', 450, 'G', 'CUP', FALSE, FALSE),
    ('찹쌀', 'GRAIN', 450, 'G', 'CUP', FALSE, FALSE),
    ('보리', 'GRAIN', 450, 'G', 'CUP', FALSE, FALSE),
    ('메밀묵', 'GRAIN', 450, 'G', 'MO', TRUE, FALSE),
    ('수수', 'GRAIN', 450, 'G', 'CUP', FALSE, FALSE),
    ('잡곡', 'GRAIN', 450, 'G', 'CUP', FALSE, FALSE),
    ('조', 'GRAIN', 450, 'G', 'CUP', FALSE, FALSE),
    ('퀴노아', 'GRAIN', 450, 'G', 'CUP', FALSE, FALSE),
    ('호밀', 'GRAIN', 450, 'G', 'CUP', FALSE, FALSE),
    ('통호밀', 'GRAIN', 450, 'G', 'CUP', FALSE, FALSE),
    ('율무', 'GRAIN', 450, 'G', 'CUP', FALSE, FALSE),
    ('강력밀가루', 'GRAIN', 450, 'G', 'CUP', TRUE, FALSE),
    ('박력밀가루', 'GRAIN', 450, 'G', 'CUP', TRUE, FALSE),
    ('중력밀가루', 'GRAIN', 450, 'G', 'CUP', TRUE, FALSE),
    ('통밀가루', 'GRAIN', 450, 'G', 'CUP', TRUE, FALSE),
    ('부침가루', 'GRAIN', 450, 'G', 'CUP', TRUE, FALSE),
    ('튀김가루', 'GRAIN', 450, 'G', 'CUP', TRUE, FALSE),
    ('빵가루', 'GRAIN', 500, 'G', 'CUP', TRUE, FALSE),
    ('밀', 'GRAIN', 450, 'G', 'CUP', TRUE, FALSE),
    ('흑밀', 'GRAIN', 450, 'G', 'CUP', TRUE, FALSE),
    ('식빵', 'GRAIN', 600, 'G', 'JANG', TRUE, FALSE),
    ('소면', 'GRAIN', 500, 'G', 'INBUN', TRUE, FALSE),
    ('파스타면', 'GRAIN', 600, 'G', 'INBUN', TRUE, FALSE),
    ('메밀면', 'GRAIN', 600, 'G', 'INBUN', TRUE, FALSE),
    ('중화면', 'GRAIN', 500, 'G', 'INBUN', TRUE, FALSE),
    ('라면사리', 'GRAIN', 400, 'G', 'BONGJI', TRUE, FALSE),
    ('우동면', 'GRAIN', 500, 'G', 'INBUN', TRUE, FALSE),
    ('떡국떡', 'GRAIN', 500, 'G', 'INBUN', FALSE, FALSE),
    ('떡볶이떡', 'GRAIN', 500, 'G', 'INBUN', FALSE, FALSE),
    ('밥', 'GRAIN', 300, 'G', 'INBUN', FALSE, FALSE),
    ('오트밀', 'GRAIN', 600, 'G', 'CUP', FALSE, FALSE),
    ('시리얼', 'GRAIN', 700, 'G', 'CUP', FALSE, FALSE),
    ('당면', 'GRAIN', 600, 'G', 'INBUN', FALSE, FALSE),
    ('그래놀라', 'GRAIN', 1200, 'G', 'CUP', FALSE, FALSE),
    ('납작당면', 'GRAIN', 750, 'G', 'INBUN', FALSE, FALSE),
    ('냉면', 'GRAIN', 600, 'G', 'INBUN', TRUE, FALSE),
    ('막국수면', 'GRAIN', 650, 'G', 'INBUN', TRUE, FALSE),
    ('옥수수면', 'GRAIN', 600, 'G', 'INBUN', FALSE, FALSE),
    ('쌀국수면', 'GRAIN', 650, 'G', 'INBUN', FALSE, FALSE),
    ('수제비', 'GRAIN', 500, 'G', 'INBUN', TRUE, FALSE),
    ('뇨키', 'GRAIN', 1200, 'G', 'INBUN', TRUE, FALSE),
    ('중면', 'GRAIN', 450, 'G', 'INBUN', TRUE, FALSE),
    ('칼국수면', 'GRAIN', 500, 'G', 'INBUN', TRUE, FALSE),
    ('쫄면', 'GRAIN', 550, 'G', 'INBUN', TRUE, FALSE),
    ('마카로니', 'GRAIN', 500, 'G', 'CUP', TRUE, FALSE),
    ('라자냐면', 'GRAIN', 800, 'G', 'JANG', TRUE, FALSE),
    ('가래떡', 'GRAIN', 600, 'G', 'GAE', FALSE, FALSE),
    ('밀떡', 'GRAIN', 450, 'G', 'INBUN', TRUE, FALSE),
    ('쌀떡', 'GRAIN', 550, 'G', 'INBUN', FALSE, FALSE),
    ('치즈떡', 'GRAIN', 800, 'G', 'GAE', TRUE, FALSE),
    ('찹쌀떡', 'GRAIN', 900, 'G', 'GAE', FALSE, FALSE),
    ('만두피', 'GRAIN', 600, 'G', 'JANG', TRUE, FALSE),
    ('라이스페이퍼', 'GRAIN', 800, 'G', 'JANG', FALSE, FALSE),
    ('또띠아', 'GRAIN', 700, 'G', 'JANG', TRUE, FALSE),
    ('타코쉘', 'GRAIN', 1200, 'G', 'GAE', FALSE, FALSE),
    ('춘권피', 'GRAIN', 800, 'G', 'JANG', TRUE, FALSE),
    ('파이피(퍼프 페이스트리)', 'GRAIN', 1500, 'G', 'JANG', TRUE, FALSE),
    ('통밀빵', 'GRAIN', 700, 'G', 'GAE', TRUE, FALSE),
    ('모닝빵', 'GRAIN', 600, 'G', 'GAE', TRUE, FALSE),
    ('베이글', 'GRAIN', 800, 'G', 'GAE', TRUE, FALSE),
    ('치아바타', 'GRAIN', 900, 'G', 'GAE', TRUE, FALSE),
    ('바게트', 'GRAIN', 800, 'G', 'GAE', TRUE, FALSE),
    ('포카치아', 'GRAIN', 1000, 'G', 'GAE', TRUE, FALSE),
    ('피타빵', 'GRAIN', 900, 'G', 'GAE', TRUE, FALSE),
    ('사워도우', 'GRAIN', 1100, 'G', 'GAE', TRUE, FALSE),
    ('피자도우', 'GRAIN', 800, 'G', 'GAE', TRUE, FALSE),

    -- 과일류
    ('감', 'FRUIT', 950, 'G', 'GAE', FALSE, FALSE),
    ('단감', 'FRUIT', 950, 'G', 'GAE', FALSE, FALSE),
    ('대봉', 'FRUIT', 950, 'G', 'GAE', FALSE, FALSE),
    ('홍시', 'FRUIT', 950, 'G', 'GAE', FALSE, FALSE),
    ('곶감', 'FRUIT', 950, 'G', 'GAE', FALSE, FALSE),
    ('거봉', 'FRUIT', 950, 'G', 'GAE', FALSE, FALSE),
    ('샤인머스캣', 'FRUIT', 950, 'G', 'GAE', FALSE, FALSE),
    ('포도', 'FRUIT', 950, 'G', 'GAE', FALSE, FALSE),
    ('청포도', 'FRUIT', 950, 'G', 'GAE', FALSE, FALSE),
    ('귤', 'FRUIT', 950, 'G', 'GAE', FALSE, FALSE),
    ('귤(천혜향)', 'FRUIT', 950, 'G', 'GAE', FALSE, FALSE),
    ('귤(한라봉)', 'FRUIT', 950, 'G', 'GAE', FALSE, FALSE),
    ('다래', 'FRUIT', 950, 'G', 'GAE', FALSE, FALSE),
    ('대추(생대추)', 'FRUIT', 950, 'G', 'AL', FALSE, FALSE),
    ('대추(말린대추)', 'FRUIT', 950, 'G', 'AL', FALSE, FALSE),
    ('대추야자', 'FRUIT', 950, 'G', 'AL', FALSE, FALSE),
    ('두리안', 'FRUIT', 950, 'G', 'GAE', FALSE, TRUE),
    ('딸기', 'FRUIT', 950, 'G', 'GAE', FALSE, FALSE),
    ('애플수박', 'FRUIT', 950, 'G', 'GAE', FALSE, FALSE),
    ('수박', 'FRUIT', 950, 'G', 'GAE', FALSE, FALSE),
    ('라즈베리', 'FRUIT', 950, 'G', 'GAE', FALSE, FALSE),
    ('블루베리', 'FRUIT', 950, 'G', 'GAE', FALSE, FALSE),
    ('산딸기', 'FRUIT', 950, 'G', 'GAE', FALSE, FALSE),
    ('아로니아', 'FRUIT', 950, 'G', 'GAE', FALSE, FALSE),
    ('크랜베리', 'FRUIT', 950, 'G', 'GAE', FALSE, FALSE),
    ('라임', 'FRUIT', 950, 'G', 'GAE', FALSE, FALSE),
    ('레몬', 'FRUIT', 950, 'G', 'GAE', FALSE, FALSE),
    ('유자', 'FRUIT', 950, 'G', 'GAE', FALSE, FALSE),
    ('탱자', 'FRUIT', 950, 'G', 'GAE', FALSE, FALSE),
    ('리치', 'FRUIT', 950, 'G', 'GAE', FALSE, FALSE),
    ('망고', 'FRUIT', 950, 'G', 'GAE', FALSE, FALSE),
    ('망고스틴', 'FRUIT', 950, 'G', 'GAE', FALSE, FALSE),
    ('머루', 'FRUIT', 950, 'G', 'GAE', FALSE, FALSE),
    ('오디', 'FRUIT', 950, 'G', 'GAE', FALSE, FALSE),
    ('오미자', 'FRUIT', 950, 'G', 'GAE', FALSE, FALSE),
    ('매실', 'FRUIT', 950, 'G', 'GAE', FALSE, FALSE),
    ('살구', 'FRUIT', 950, 'G', 'GAE', FALSE, FALSE),
    ('앵두', 'FRUIT', 950, 'G', 'GAE', FALSE, FALSE),
    ('자두', 'FRUIT', 950, 'G', 'GAE', FALSE, FALSE),
    ('체리', 'FRUIT', 950, 'G', 'GAE', FALSE, FALSE),
    ('버찌', 'FRUIT', 950, 'G', 'GAE', FALSE, FALSE),
    ('모과', 'FRUIT', 950, 'G', 'GAE', FALSE, FALSE),
    ('무화과', 'FRUIT', 950, 'G', 'GAE', FALSE, FALSE),
    ('배', 'FRUIT', 950, 'G', 'GAE', FALSE, FALSE),
    ('사과', 'FRUIT', 950, 'G', 'GAE', FALSE, FALSE),
    ('멜론', 'FRUIT', 950, 'G', 'GAE', FALSE, FALSE),
    ('참외', 'FRUIT', 950, 'G', 'GAE', FALSE, FALSE),
    ('바나나', 'FRUIT', 950, 'G', 'GAE', FALSE, FALSE),
    ('복숭아(백도)', 'FRUIT', 950, 'G', 'GAE', TRUE, FALSE),
    ('복숭아(천도)', 'FRUIT', 950, 'G', 'GAE', TRUE, FALSE),
    ('복숭아(황도)', 'FRUIT', 950, 'G', 'GAE', TRUE, FALSE),
    ('용과(백)', 'FRUIT', 950, 'G', 'GAE', FALSE, FALSE),
    ('용과(적)', 'FRUIT', 950, 'G', 'GAE', FALSE, FALSE),
    ('용과(황)', 'FRUIT', 950, 'G', 'GAE', FALSE, FALSE),
    ('잭프루트', 'FRUIT', 950, 'G', 'GAE', FALSE, FALSE),
    ('파파야', 'FRUIT', 950, 'G', 'GAE', FALSE, FALSE),
    ('파인애플', 'FRUIT', 950, 'G', 'GAE', FALSE, FALSE),
    ('자몽', 'FRUIT', 950, 'G', 'GAE', FALSE, FALSE),
    ('오렌지', 'FRUIT', 950, 'G', 'GAE', FALSE, FALSE),
    ('석류', 'FRUIT', 950, 'G', 'GAE', FALSE, FALSE),
    ('산수유', 'FRUIT', 950, 'G', 'GAE', FALSE, FALSE),
    ('아보카도', 'FRUIT', 950, 'G', 'GAE', FALSE, FALSE),

    -- 당류, 잼, 스프레드 및 제과재료
    ('각설탕', 'SUGAR', 250, 'G', 'GAE', FALSE, FALSE),
    ('백설탕', 'SUGAR', 250, 'G', 'TBSP', FALSE, FALSE),
    ('황설탕', 'SUGAR', 250, 'G', 'TBSP', FALSE, FALSE),
    ('흑설탕', 'SUGAR', 250, 'G', 'TBSP', FALSE, FALSE),
    ('빙설탕', 'SUGAR', 250, 'G', 'TBSP', FALSE, FALSE),
    ('꿀', 'SUGAR', 250, 'G', 'TBSP', FALSE, FALSE),
    ('당밀', 'SUGAR', 250, 'G', 'TBSP', FALSE, FALSE),
    ('분당(슈가파우더)', 'SUGAR', 250, 'G', 'TBSP', FALSE, FALSE),
    ('아가베 시럽', 'SUGAR', 250, 'G', 'TBSP', FALSE, FALSE),
    ('알룰로스', 'SUGAR', 250, 'G', 'TBSP', FALSE, FALSE),
    ('메이플 시럽', 'SUGAR', 250, 'G', 'TBSP', FALSE, FALSE),
    ('스테비아', 'SUGAR', 250, 'G', 'TSP', FALSE, FALSE),
    ('딸기잼', 'SUGAR', 800, 'G', 'TBSP', FALSE, FALSE),
    ('사과잼', 'SUGAR', 800, 'G', 'TBSP', FALSE, FALSE),
    ('블루베리잼', 'SUGAR', 900, 'G', 'TBSP', FALSE, FALSE),
    ('라즈베리잼', 'SUGAR', 1000, 'G', 'TBSP', FALSE, FALSE),
    ('무화과잼', 'SUGAR', 1100, 'G', 'TBSP', FALSE, FALSE),
    ('오렌지 마멀레이드', 'SUGAR', 950, 'G', 'TBSP', FALSE, FALSE),
    ('카야잼', 'SUGAR', 1200, 'G', 'TBSP', TRUE, FALSE),
    ('누텔라', 'SUGAR', 1300, 'G', 'TBSP', TRUE, FALSE),
    ('로투스 스프레드', 'SUGAR', 1200, 'G', 'TBSP', TRUE, FALSE),
    ('말차 크림 스프레드', 'SUGAR', 1400, 'G', 'TBSP', TRUE, FALSE),
    ('아몬드가루', 'NUT_AND_SEED', 2200, 'G', 'CUP', TRUE, FALSE),
    ('아몬드버터', 'NUT_AND_SEED', 2500, 'G', 'TBSP', TRUE, FALSE),
    ('커버춰 초콜릿', 'SUGAR', 1800, 'G', 'CUP', TRUE, FALSE),
    ('초코칩', 'SUGAR', 1500, 'G', 'CUP', TRUE, FALSE),

    -- 두류 및 콩가공품
    ('강낭콩', 'LEGUME', 1100, 'G', 'CUP', TRUE, FALSE),
    ('검은콩', 'LEGUME', 1100, 'G', 'CUP', TRUE, FALSE),
    ('녹두', 'LEGUME', 1100, 'G', 'CUP', TRUE, FALSE),
    ('대두(백태)', 'LEGUME', 1100, 'G', 'CUP', TRUE, FALSE),
    ('렌틸콩', 'LEGUME', 1100, 'G', 'CUP', TRUE, FALSE),
    ('병아리콩', 'LEGUME', 1100, 'G', 'CUP', TRUE, FALSE),
    ('완두', 'LEGUME', 1100, 'G', 'CUP', TRUE, FALSE),
    ('팥', 'LEGUME', 1100, 'G', 'CUP', TRUE, FALSE),
    ('건두부', 'PROCESSED_LEGUME', 900, 'G', 'MO', TRUE, FALSE),
    ('두부', 'PROCESSED_LEGUME', 900, 'G', 'MO', TRUE, FALSE),
    ('순두부', 'PROCESSED_LEGUME', 900, 'G', 'MO', TRUE, FALSE),
    ('연두부', 'PROCESSED_LEGUME', 900, 'G', 'MO', TRUE, FALSE),
    ('유부', 'PROCESSED_LEGUME', 900, 'G', 'GAE', TRUE, FALSE),
    ('두유', 'PROCESSED_LEGUME', 900, 'G', 'CUP', TRUE, FALSE),
    ('녹두묵', 'PROCESSED_LEGUME', 900, 'G', 'MO', TRUE, FALSE),
    ('메주', 'PROCESSED_LEGUME', 900, 'G', 'GAE', TRUE, FALSE),
    ('나또', 'PROCESSED_LEGUME', 900, 'G', 'GAE', TRUE, TRUE),
    ('청국장', 'PROCESSED_LEGUME', 900, 'G', 'GAE', TRUE, TRUE),
    ('콩고기', 'PROCESSED_LEGUME', 900, 'G', 'INBUN', TRUE, FALSE),
    ('콩비지', 'PROCESSED_LEGUME', 900, 'G', 'CUP', TRUE, FALSE),

    -- 버섯류
    ('검은비늘버섯', 'MUSHROOM', 1200, 'G', 'GAE', FALSE, FALSE),
    ('나도팽나무버섯', 'MUSHROOM', 1200, 'G', 'GAE', FALSE, FALSE),
    ('뽕나무버섯', 'MUSHROOM', 1200, 'G', 'GAE', FALSE, FALSE),
    ('꾀꼬리버섯(샤방테렐)', 'MUSHROOM', 1200, 'G', 'GAE', FALSE, FALSE),
    ('꽃송이버섯', 'MUSHROOM', 1200, 'G', 'GAE', FALSE, FALSE),
    ('영지버섯', 'MUSHROOM', 1200, 'G', 'GAE', FALSE, FALSE),
    ('상황버섯', 'MUSHROOM', 1200, 'G', 'GAE', FALSE, FALSE),
    ('동충하초', 'MUSHROOM', 1200, 'G', 'GAE', FALSE, FALSE),
    ('느타리버섯(애느타리)', 'MUSHROOM', 1200, 'G', 'GAE', FALSE, FALSE),
    ('느타리버섯(율무느타리)', 'MUSHROOM', 1200, 'G', 'GAE', FALSE, FALSE),
    ('능이버섯(향버섯)', 'MUSHROOM', 1200, 'G', 'GAE', FALSE, FALSE),
    ('송이버섯', 'MUSHROOM', 1200, 'G', 'GAE', FALSE, FALSE),
    ('버들송이버섯', 'MUSHROOM', 1200, 'G', 'GAE', FALSE, FALSE),
    ('노루궁뎅이버섯', 'MUSHROOM', 1200, 'G', 'GAE', FALSE, FALSE),
    ('백목이버섯(은이버섯)', 'MUSHROOM', 1200, 'G', 'GAE', FALSE, FALSE),
    ('목이버섯', 'MUSHROOM', 1200, 'G', 'GAE', FALSE, FALSE),
    ('만가닥버섯', 'MUSHROOM', 1200, 'G', 'GAE', FALSE, FALSE),
    ('밤버섯', 'MUSHROOM', 1200, 'G', 'GAE', FALSE, FALSE),
    ('아위버섯', 'MUSHROOM', 1200, 'G', 'GAE', FALSE, FALSE),
    ('싸리버섯', 'MUSHROOM', 1200, 'G', 'GAE', FALSE, FALSE),
    ('석이버섯', 'MUSHROOM', 1200, 'G', 'GAE', FALSE, FALSE),
    ('풀버섯', 'MUSHROOM', 1200, 'G', 'GAE', FALSE, FALSE),
    ('포타벨라', 'MUSHROOM', 1200, 'G', 'GAE', FALSE, FALSE),
    ('잎새버섯', 'MUSHROOM', 1200, 'G', 'GAE', FALSE, FALSE),
    ('새송이버섯(큰느타리버섯)', 'MUSHROOM', 1200, 'G', 'GAE', FALSE, FALSE),
    ('양송이버섯', 'MUSHROOM', 1200, 'G', 'GAE', FALSE, FALSE),
    ('표고버섯', 'MUSHROOM', 1200, 'G', 'GAE', FALSE, FALSE),
    ('팽이버섯', 'MUSHROOM', 1200, 'G', 'GAE', FALSE, FALSE),
    ('포르치니 버섯', 'MUSHROOM', 1200, 'G', 'GAE', FALSE, FALSE),
    ('트러플(송로버섯)', 'MUSHROOM', 1200, 'G', 'GAE', FALSE, FALSE),

    -- 유제품 및 치즈류
    ('우유', 'MILK', 300, 'ML', 'CUP', TRUE, FALSE),
    ('버터', 'MILK', 1200, 'G', 'TBSP', TRUE, FALSE),
    ('무염버터', 'MILK', 1400, 'G', 'TBSP', TRUE, FALSE),
    ('체다치즈', 'MILK', 1500, 'G', 'JANG', TRUE, FALSE),
    ('모짜렐라치즈', 'MILK', 1600, 'G', 'CUP', TRUE, FALSE),
    ('파마산 치즈', 'MILK', 2000, 'G', 'TBSP', TRUE, FALSE),
    ('리코타 치즈', 'MILK', 1800, 'G', 'CUP', TRUE, FALSE),
    ('슬라이스 치즈', 'MILK', 1400, 'G', 'JANG', TRUE, FALSE),
    ('부라타치즈', 'MILK', 2800, 'G', 'GAE', TRUE, FALSE),
    ('페타치즈', 'MILK', 2200, 'G', 'CUP', TRUE, FALSE),
    ('브리 치즈', 'MILK', 2500, 'G', 'GAE', TRUE, FALSE),
    ('카망베르 치즈', 'MILK', 2500, 'G', 'GAE', TRUE, FALSE),
    ('마스카포네 치즈', 'MILK', 2000, 'G', 'CUP', TRUE, FALSE),
    ('고트 치즈', 'MILK', 3000, 'G', 'CUP', TRUE, FALSE),
    ('하바티 치즈', 'MILK', 2200, 'G', 'JANG', TRUE, FALSE),
    ('에멘탈 치즈', 'MILK', 2400, 'G', 'CUP', TRUE, FALSE),
    ('고다 치즈', 'MILK', 2200, 'G', 'CUP', TRUE, FALSE),
    ('생크림', 'MILK', 800, 'ML', 'CUP', TRUE, FALSE),
    ('휘핑크림', 'MILK', 900, 'ML', 'CUP', TRUE, FALSE),
    ('사워크림', 'MILK', 1100, 'G', 'TBSP', TRUE, FALSE),
    ('에바포레이트 밀크', 'MILK', 800, 'ML', 'CUP', TRUE, FALSE),
    ('연유', 'MILK', 700, 'G', 'TBSP', TRUE, FALSE),
    ('요거트', 'MILK', 500, 'G', 'GAE', TRUE, FALSE),
    ('그릭요거트', 'MILK', 900, 'G', 'GAE', TRUE, FALSE),

    -- 유지류
    ('기 버터', 'FAT_AND_OIL', 2500, 'G', 'TBSP', TRUE, FALSE),
    ('덕팻(오리기름)', 'FAT_AND_OIL', 850, 'ML', 'TBSP', FALSE, FALSE),
    ('닭기름', 'FAT_AND_OIL', 850, 'ML', 'TBSP', TRUE, FALSE),
    ('돼지기름', 'FAT_AND_OIL', 850, 'ML', 'TBSP', TRUE, FALSE),
    ('쇠기름', 'FAT_AND_OIL', 850, 'ML', 'TBSP', TRUE, FALSE),
    ('연어기름', 'FAT_AND_OIL', 850, 'ML', 'TBSP', FALSE, FALSE),
    ('면실유', 'FAT_AND_OIL', 850, 'ML', 'TBSP', FALSE, FALSE),
    ('미강유(쌀겨기름)', 'FAT_AND_OIL', 850, 'ML', 'TBSP', FALSE, FALSE),
    ('팜유', 'FAT_AND_OIL', 850, 'ML', 'TBSP', FALSE, FALSE),
    ('혼합식물성유', 'FAT_AND_OIL', 850, 'ML', 'TBSP', FALSE, FALSE),
    ('들기름', 'FAT_AND_OIL', 850, 'ML', 'TBSP', FALSE, FALSE),
    ('참기름', 'FAT_AND_OIL', 850, 'ML', 'TBSP', FALSE, FALSE),
    ('콩기름', 'FAT_AND_OIL', 850, 'ML', 'TBSP', TRUE, FALSE),
    ('유채씨기름', 'FAT_AND_OIL', 850, 'ML', 'TBSP', FALSE, FALSE),
    ('잇꽃씨기름', 'FAT_AND_OIL', 850, 'ML', 'TBSP', FALSE, FALSE),
    ('포도씨유', 'FAT_AND_OIL', 850, 'ML', 'TBSP', FALSE, FALSE),
    ('해바라기유', 'FAT_AND_OIL', 850, 'ML', 'TBSP', FALSE, FALSE),
    ('옥수수기름', 'FAT_AND_OIL', 850, 'ML', 'TBSP', FALSE, FALSE),
    ('아몬드유', 'FAT_AND_OIL', 850, 'ML', 'TBSP', FALSE, FALSE),
    ('아보카도유', 'FAT_AND_OIL', 850, 'ML', 'TBSP', FALSE, FALSE),
    ('아마씨유', 'FAT_AND_OIL', 850, 'ML', 'TBSP', FALSE, FALSE),
    ('올리브유', 'FAT_AND_OIL', 850, 'ML', 'TBSP', FALSE, FALSE),
    ('코코넛유', 'FAT_AND_OIL', 850, 'ML', 'TBSP', FALSE, FALSE),
    ('피스타치오유', 'FAT_AND_OIL', 850, 'ML', 'TBSP', FALSE, FALSE),
    ('호두유', 'FAT_AND_OIL', 850, 'ML', 'TBSP', TRUE, FALSE),
    ('땅콩기름', 'FAT_AND_OIL', 850, 'ML', 'TBSP', TRUE, FALSE),
    ('복숭아씨기름', 'FAT_AND_OIL', 850, 'ML', 'TBSP', TRUE, FALSE),
    ('트러플 오일', 'FAT_AND_OIL', 850, 'ML', 'TBSP', FALSE, FALSE),

    -- 육류 및 가공육/냉동가공품
    ('고래고기', 'MEAT', 3400, 'G', 'INBUN', FALSE, TRUE),
    ('닭고기', 'MEAT', 3400, 'G', 'MARI', TRUE, FALSE),
    ('닭가슴살', 'MEAT', 1200, 'G', 'GAE', TRUE, FALSE),
    ('훈제 닭가슴살', 'MEAT', 1400, 'G', 'GAE', TRUE, FALSE),
    ('닭고기(간)', 'MEAT', 3400, 'G', 'INBUN', TRUE, TRUE),
    ('닭고기(모래주머니)', 'MEAT', 3400, 'G', 'INBUN', TRUE, FALSE),
    ('닭고기(발)', 'MEAT', 3400, 'G', 'INBUN', TRUE, TRUE),
    ('닭고기(염통)', 'MEAT', 3400, 'G', 'INBUN', TRUE, FALSE),
    ('돼지고기', 'MEAT', 3400, 'G', 'INBUN', TRUE, FALSE),
    ('돼지고기(갈비)', 'MEAT', 3400, 'G', 'INBUN', TRUE, FALSE),
    ('돼지고기(간)', 'MEAT', 3400, 'G', 'INBUN', TRUE, TRUE),
    ('돼지고기(곱창)', 'MEAT', 3400, 'G', 'INBUN', TRUE, TRUE),
    ('돼지고기(등심)', 'MEAT', 3400, 'G', 'INBUN', TRUE, FALSE),
    ('돼지고기(뒷다리살)', 'MEAT', 3400, 'G', 'INBUN', TRUE, FALSE),
    ('돼지고기(막창)', 'MEAT', 3400, 'G', 'INBUN', TRUE, TRUE),
    ('돼지고기(머리고기)', 'MEAT', 3400, 'G', 'INBUN', TRUE, FALSE),
    ('돼지고기(목살)', 'MEAT', 3400, 'G', 'INBUN', TRUE, FALSE),
    ('돼지고기(발)', 'MEAT', 3400, 'G', 'GAE', TRUE, FALSE),
    ('돼지고기(삼겹살)', 'MEAT', 3400, 'G', 'INBUN', TRUE, FALSE),
    ('대패삼겹살', 'MEAT', 2200, 'G', 'INBUN', TRUE, FALSE),
    ('돼지고기(수육용)', 'MEAT', 3400, 'G', 'INBUN', TRUE, FALSE),
    ('돼지고기(앞다리살)', 'MEAT', 3400, 'G', 'INBUN', TRUE, FALSE),
    ('돼지고기(염통)', 'MEAT', 3400, 'G', 'INBUN', TRUE, FALSE),
    ('돼지고기(오소리감투)', 'MEAT', 3400, 'G', 'INBUN', TRUE, TRUE),
    ('돼지고기(허파)', 'MEAT', 3400, 'G', 'INBUN', TRUE, TRUE),
    ('돼지고기(항정살)', 'MEAT', 3400, 'G', 'INBUN', TRUE, FALSE),
    ('다진 돼지고기', 'MEAT', 1800, 'G', 'INBUN', TRUE, FALSE),
    ('풀드포크', 'MEAT', 3000, 'G', 'INBUN', TRUE, FALSE),
    ('소고기', 'MEAT', 3400, 'G', 'INBUN', TRUE, FALSE),
    ('차돌박이', 'MEAT', 3800, 'G', 'INBUN', TRUE, FALSE),
    ('샤브샤브용 소고기', 'MEAT', 3500, 'G', 'INBUN', TRUE, FALSE),
    ('다진 소고기', 'MEAT', 3200, 'G', 'INBUN', TRUE, FALSE),
    ('소고기(갈비살)', 'MEAT', 3400, 'G', 'INBUN', TRUE, FALSE),
    ('소고기(간)', 'MEAT', 3400, 'G', 'INBUN', TRUE, TRUE),
    ('소고기(곱창)', 'MEAT', 3400, 'G', 'INBUN', TRUE, TRUE),
    ('소고기(등심살)', 'MEAT', 3400, 'G', 'INBUN', TRUE, FALSE),
    ('소고기(목심살)', 'MEAT', 3400, 'G', 'INBUN', TRUE, FALSE),
    ('소고기(사태살)', 'MEAT', 3400, 'G', 'INBUN', TRUE, FALSE),
    ('소고기(설도살)', 'MEAT', 3400, 'G', 'INBUN', TRUE, FALSE),
    ('소고기(선지)', 'MEAT', 3400, 'G', 'INBUN', TRUE, TRUE),
    ('소고기(안심살)', 'MEAT', 3400, 'G', 'INBUN', TRUE, FALSE),
    ('소고기(앞다리살)', 'MEAT', 3400, 'G', 'INBUN', TRUE, FALSE),
    ('소고기(양지살)', 'MEAT', 3400, 'G', 'INBUN', TRUE, FALSE),
    ('소고기(염통)', 'MEAT', 3400, 'G', 'INBUN', TRUE, FALSE),
    ('소고기(우둔살)', 'MEAT', 3400, 'G', 'INBUN', TRUE, FALSE),
    ('소고기(위)', 'MEAT', 3400, 'G', 'INBUN', TRUE, TRUE),
    ('소고기(천엽)', 'MEAT', 3400, 'G', 'INBUN', TRUE, TRUE),
    ('소고기(채끝살)', 'MEAT', 3400, 'G', 'INBUN', TRUE, FALSE),
    ('소고기(허파)', 'MEAT', 3400, 'G', 'INBUN', TRUE, TRUE),
    ('소고기(혀)', 'MEAT', 3400, 'G', 'INBUN', TRUE, TRUE),
    ('양고기', 'MEAT', 3400, 'G', 'INBUN', FALSE, TRUE),
    ('오리고기', 'MEAT', 3400, 'G', 'INBUN', FALSE, FALSE),
    ('훈제오리', 'MEAT', 3500, 'G', 'INBUN', FALSE, FALSE),
    ('관찰레', 'MEAT', 4500, 'G', 'INBUN', TRUE, FALSE),
    ('하몽', 'MEAT', 6000, 'G', 'JANG', TRUE, FALSE),
    ('프로슈토', 'MEAT', 5500, 'G', 'JANG', TRUE, FALSE),
    ('살라미', 'MEAT', 3500, 'G', 'JANG', TRUE, FALSE),
    ('페퍼로니', 'MEAT', 3200, 'G', 'JANG', TRUE, FALSE),
    ('초리조', 'MEAT', 3800, 'G', 'INBUN', TRUE, FALSE),
    ('판체타', 'MEAT', 4000, 'G', 'INBUN', TRUE, FALSE),
    ('베이컨', 'MEAT', 2800, 'G', 'JANG', TRUE, FALSE),
    ('비엔나소시지', 'MEAT', 2200, 'G', 'GAE', TRUE, FALSE),
    ('햄', 'MEAT', 2000, 'G', 'GAE', TRUE, FALSE),
    ('통조림햄(스팸)', 'MEAT', 2200, 'G', 'GAE', TRUE, FALSE),
    ('만두', 'MEAT', 1500, 'G', 'GAE', TRUE, FALSE),
    ('미트볼', 'MEAT', 2000, 'G', 'GAE', TRUE, FALSE),
    ('떡갈비', 'MEAT', 2500, 'G', 'GAE', TRUE, FALSE),

    -- 채소류, 김치 및 채소 가공품
    ('갓', 'VEGETABLE', 750, 'G', 'GAE', FALSE, FALSE),
    ('고들빼기', 'VEGETABLE', 750, 'G', 'GAE', FALSE, FALSE),
    ('두릅', 'VEGETABLE', 750, 'G', 'GAE', FALSE, FALSE),
    ('머위', 'VEGETABLE', 750, 'G', 'GAE', FALSE, FALSE),
    ('엉겅퀴', 'VEGETABLE', 750, 'G', 'GAE', FALSE, FALSE),
    ('취나물', 'VEGETABLE', 750, 'G', 'GAE', FALSE, FALSE),
    ('쑥', 'VEGETABLE', 750, 'G', 'GAE', FALSE, FALSE),
    ('쑥갓', 'VEGETABLE', 750, 'G', 'GAE', FALSE, FALSE),
    ('고사리', 'VEGETABLE', 750, 'G', 'GAE', FALSE, FALSE),
    ('고구마줄기', 'VEGETABLE', 750, 'G', 'JULGI', FALSE, FALSE),
    ('고추', 'VEGETABLE', 750, 'G', 'GAE', FALSE, FALSE),
    ('고추(꽈리고추)', 'VEGETABLE', 750, 'G', 'GAE', FALSE, FALSE),
    ('고추(오이고추)', 'VEGETABLE', 750, 'G', 'GAE', FALSE, FALSE),
    ('고추(청양고추)', 'VEGETABLE', 750, 'G', 'GAE', FALSE, FALSE),
    ('고추(풋고추)', 'VEGETABLE', 750, 'G', 'GAE', FALSE, FALSE),
    ('고추(홍고추)', 'VEGETABLE', 750, 'G', 'GAE', FALSE, FALSE),
    ('겨자', 'VEGETABLE', 750, 'G', 'GAE', FALSE, FALSE),
    ('산초', 'VEGETABLE', 750, 'G', 'GAE', FALSE, TRUE),
    ('곰취', 'VEGETABLE', 750, 'G', 'JANG', FALSE, FALSE),
    ('깻잎', 'VEGETABLE', 750, 'G', 'JANG', FALSE, TRUE),
    ('명이나물', 'VEGETABLE', 750, 'G', 'JANG', FALSE, FALSE),
    ('콩잎', 'VEGETABLE', 750, 'G', 'JANG', FALSE, FALSE),
    ('냉이', 'VEGETABLE', 750, 'G', 'GAE', FALSE, FALSE),
    ('민들레', 'VEGETABLE', 750, 'G', 'GAE', FALSE, FALSE),
    ('방아', 'VEGETABLE', 750, 'G', 'GAE', FALSE, TRUE),
    ('뽕잎', 'VEGETABLE', 750, 'G', 'JANG', FALSE, FALSE),
    ('당근', 'VEGETABLE', 750, 'G', 'GAE', FALSE, TRUE),
    ('비트', 'VEGETABLE', 750, 'G', 'GAE', FALSE, FALSE),
    ('콜라비', 'VEGETABLE', 750, 'G', 'GAE', FALSE, FALSE),
    ('더덕', 'VEGETABLE', 750, 'G', 'GAE', FALSE, FALSE),
    ('도라지', 'VEGETABLE', 750, 'G', 'GAE', FALSE, FALSE),
    ('우엉', 'VEGETABLE', 750, 'G', 'GAE', FALSE, FALSE),
    ('연근', 'VEGETABLE', 750, 'G', 'GAE', FALSE, FALSE),
    ('마늘', 'VEGETABLE', 750, 'G', 'AL', FALSE, FALSE),
    ('다진마늘', 'VEGETABLE', 750, 'G', 'TBSP', FALSE, FALSE),
    ('냉동다진마늘', 'VEGETABLE', 1200, 'G', 'TBSP', FALSE, FALSE),
    ('마늘종', 'VEGETABLE', 750, 'G', 'JULGI', FALSE, FALSE),
    ('양파', 'VEGETABLE', 750, 'G', 'GAE', FALSE, FALSE),
    ('대파', 'VEGETABLE', 750, 'G', 'JULGI', FALSE, FALSE),
    ('쪽파', 'VEGETABLE', 750, 'G', 'JULGI', FALSE, FALSE),
    ('파', 'VEGETABLE', 750, 'G', 'JULGI', FALSE, FALSE),
    ('샬롯', 'VEGETABLE', 750, 'G', 'GAE', FALSE, FALSE),
    ('리크', 'VEGETABLE', 750, 'G', 'JULGI', FALSE, FALSE),
    ('무', 'VEGETABLE', 750, 'G', 'GAE', FALSE, FALSE),
    ('무순', 'VEGETABLE', 750, 'G', 'GAE', FALSE, FALSE),
    ('무청', 'VEGETABLE', 750, 'G', 'JULGI', FALSE, FALSE),
    ('무말랭이', 'VEGETABLE', 750, 'G', 'GAE', FALSE, FALSE),
    ('순무', 'VEGETABLE', 750, 'G', 'GAE', FALSE, FALSE),
    ('총각무', 'VEGETABLE', 750, 'G', 'GAE', FALSE, FALSE),
    ('열무', 'VEGETABLE', 750, 'G', 'GAE', FALSE, FALSE),
    ('쌈무', 'VEGETABLE', 750, 'G', 'JANG', FALSE, FALSE),
    ('단무지', 'VEGETABLE', 750, 'G', 'GAE', FALSE, FALSE),
    ('락교', 'VEGETABLE', 750, 'G', 'AL', FALSE, FALSE),
    ('미나리', 'VEGETABLE', 750, 'G', 'JULGI', FALSE, FALSE),
    ('부추', 'VEGETABLE', 750, 'G', 'JULGI', FALSE, FALSE),
    ('바질', 'VEGETABLE', 750, 'G', 'GAE', FALSE, FALSE),
    ('루꼴라', 'VEGETABLE', 750, 'G', 'GAE', FALSE, FALSE),
    ('고수', 'VEGETABLE', 750, 'G', 'GAE', FALSE, TRUE),
    ('딜', 'VEGETABLE', 750, 'G', 'GAE', FALSE, FALSE),
    ('파슬리', 'VEGETABLE', 750, 'G', 'GAE', FALSE, FALSE),
    ('타임', 'VEGETABLE', 750, 'G', 'GAE', FALSE, FALSE),
    ('월계수', 'VEGETABLE', 750, 'G', 'JANG', FALSE, FALSE),
    ('오레가노', 'VEGETABLE', 750, 'G', 'GAE', FALSE, FALSE),
    ('민트', 'VEGETABLE', 750, 'G', 'GAE', FALSE, TRUE),
    ('페퍼민트', 'VEGETABLE', 750, 'G', 'GAE', FALSE, TRUE),
    ('라벤더', 'VEGETABLE', 750, 'G', 'GAE', FALSE, FALSE),
    ('레몬그라스(시트로넬라)', 'VEGETABLE', 750, 'G', 'JULGI', FALSE, FALSE),
    ('차이브', 'VEGETABLE', 750, 'G', 'JULGI', FALSE, FALSE),
    ('배추', 'VEGETABLE', 750, 'G', 'GAE', FALSE, FALSE),
    ('배추(우거지)', 'VEGETABLE', 750, 'G', 'GAE', FALSE, FALSE),
    ('배추(봄동)', 'VEGETABLE', 750, 'G', 'GAE', FALSE, FALSE),
    ('배추(얼갈이배추)', 'VEGETABLE', 750, 'G', 'GAE', FALSE, FALSE),
    ('양배추', 'VEGETABLE', 750, 'G', 'GAE', FALSE, FALSE),
    ('방울양배추', 'VEGETABLE', 750, 'G', 'GAE', FALSE, FALSE),
    ('청경채', 'VEGETABLE', 750, 'G', 'GAE', FALSE, FALSE),
    ('케일', 'VEGETABLE', 750, 'G', 'JANG', FALSE, FALSE),
    ('치커리', 'VEGETABLE', 750, 'G', 'GAE', FALSE, FALSE),
    ('아욱', 'VEGETABLE', 750, 'G', 'GAE', FALSE, FALSE),
    ('시금치', 'VEGETABLE', 750, 'G', 'GAE', FALSE, FALSE),
    ('상추(로메인)', 'VEGETABLE', 750, 'G', 'JANG', FALSE, FALSE),
    ('샐러드채소', 'VEGETABLE', 750, 'G', 'CUP', FALSE, FALSE),
    ('어린잎채소', 'VEGETABLE', 750, 'G', 'CUP', FALSE, FALSE),
    ('라디키오', 'VEGETABLE', 750, 'G', 'GAE', FALSE, FALSE),
    ('엔다이브', 'VEGETABLE', 750, 'G', 'GAE', FALSE, FALSE),
    ('물냉이(크레스)', 'VEGETABLE', 750, 'G', 'GAE', FALSE, FALSE),
    ('브로콜리', 'VEGETABLE', 750, 'G', 'GAE', FALSE, TRUE),
    ('콜리플라워', 'VEGETABLE', 750, 'G', 'GAE', FALSE, FALSE),
    ('아티초크', 'VEGETABLE', 750, 'G', 'GAE', FALSE, FALSE),
    ('박', 'VEGETABLE', 750, 'G', 'GAE', FALSE, FALSE),
    ('죽순', 'VEGETABLE', 750, 'G', 'GAE', FALSE, FALSE),
    ('알로에', 'VEGETABLE', 750, 'G', 'JULGI', FALSE, FALSE),
    ('사탕수수', 'VEGETABLE', 750, 'G', 'JULGI', FALSE, FALSE),
    ('사탕무', 'VEGETABLE', 750, 'G', 'GAE', FALSE, FALSE),
    ('꾸지뽕', 'VEGETABLE', 750, 'G', 'AL', FALSE, FALSE),
    ('차요테', 'VEGETABLE', 750, 'G', 'GAE', FALSE, FALSE),
    ('물밤(마름)', 'VEGETABLE', 750, 'G', 'AL', FALSE, FALSE),
    ('샐러리', 'VEGETABLE', 750, 'G', 'JULGI', FALSE, TRUE),
    ('생강', 'VEGETABLE', 750, 'G', 'GAE', FALSE, TRUE),
    ('숙주나물', 'VEGETABLE', 750, 'G', 'INBUN', FALSE, FALSE),
    ('콩나물', 'VEGETABLE', 750, 'G', 'INBUN', FALSE, FALSE),
    ('참나물', 'VEGETABLE', 750, 'G', 'GAE', FALSE, FALSE),
    ('오이', 'VEGETABLE', 750, 'G', 'GAE', FALSE, TRUE),
    ('늙은오이', 'VEGETABLE', 750, 'G', 'GAE', FALSE, TRUE),
    ('피망', 'VEGETABLE', 750, 'G', 'GAE', FALSE, TRUE),
    ('파프리카', 'VEGETABLE', 750, 'G', 'GAE', FALSE, TRUE),
    ('토마토', 'VEGETABLE', 750, 'G', 'GAE', TRUE, FALSE),
    ('방울토마토', 'VEGETABLE', 750, 'G', 'AL', TRUE, FALSE),
    ('가지', 'VEGETABLE', 750, 'G', 'GAE', FALSE, TRUE),
    ('페넬(회향)', 'VEGETABLE', 750, 'G', 'GAE', FALSE, FALSE),
    ('배추김치', 'VEGETABLE', 800, 'G', 'INBUN', FALSE, FALSE),
    ('깍두기', 'VEGETABLE', 800, 'G', 'INBUN', FALSE, FALSE),
    ('동치미', 'VEGETABLE', 700, 'G', 'INBUN', FALSE, FALSE),
    ('총각김치', 'VEGETABLE', 850, 'G', 'INBUN', FALSE, FALSE),
    ('열무김치', 'VEGETABLE', 800, 'G', 'INBUN', FALSE, FALSE),
    ('부추김치', 'VEGETABLE', 900, 'G', 'INBUN', FALSE, FALSE),
    ('오이김치', 'VEGETABLE', 850, 'G', 'INBUN', FALSE, FALSE),
    ('파김치', 'VEGETABLE', 1000, 'G', 'INBUN', FALSE, FALSE),
    ('피클', 'VEGETABLE', 700, 'G', 'INBUN', FALSE, FALSE),
    ('장아찌', 'VEGETABLE', 900, 'G', 'INBUN', FALSE, FALSE),
    ('냉동채소', 'VEGETABLE', 800, 'G', 'CUP', FALSE, FALSE),
    ('옥수수통조림', 'VEGETABLE', 500, 'G', 'GAE', FALSE, FALSE),

    -- 해조류
    ('가시파래(감태)', 'SEAWEED', 2500, 'G', 'JANG', FALSE, FALSE),
    ('김', 'SEAWEED', 2500, 'G', 'JANG', FALSE, FALSE),
    ('다시마', 'SEAWEED', 2500, 'G', 'JANG', FALSE, FALSE),
    ('매생이', 'SEAWEED', 2500, 'G', 'GAE', FALSE, FALSE),
    ('미역', 'SEAWEED', 2500, 'G', 'GAE', FALSE, FALSE),
    ('바다포도', 'SEAWEED', 2500, 'G', 'GAE', FALSE, FALSE),
    ('우뭇가사리(우무)', 'SEAWEED', 2500, 'G', 'GAE', FALSE, FALSE),
    ('파래', 'SEAWEED', 2500, 'G', 'GAE', FALSE, FALSE),
    ('톳', 'SEAWEED', 2500, 'G', 'GAE', FALSE, FALSE),

    -- 수산물, 어류, 건어물 및 통조림류
    ('가자미', 'FISH_AND_OTHER_SEAFOOD', 2800, 'G', 'MARI', FALSE, FALSE),
    ('광어(넙치)', 'FISH_AND_OTHER_SEAFOOD', 2800, 'G', 'MARI', FALSE, FALSE),
    ('도다리', 'FISH_AND_OTHER_SEAFOOD', 2800, 'G', 'MARI', FALSE, FALSE),
    ('돔', 'FISH_AND_OTHER_SEAFOOD', 2800, 'G', 'MARI', FALSE, FALSE),
    ('우럭', 'FISH_AND_OTHER_SEAFOOD', 2800, 'G', 'MARI', FALSE, FALSE),
    ('복어', 'FISH_AND_OTHER_SEAFOOD', 2800, 'G', 'MARI', FALSE, FALSE),
    ('볼락', 'FISH_AND_OTHER_SEAFOOD', 2800, 'G', 'MARI', FALSE, FALSE),
    ('임연수', 'FISH_AND_OTHER_SEAFOOD', 2800, 'G', 'MARI', FALSE, FALSE),
    ('쥐치', 'FISH_AND_OTHER_SEAFOOD', 2800, 'G', 'MARI', FALSE, FALSE),
    ('고등어', 'FISH_AND_OTHER_SEAFOOD', 2800, 'G', 'MARI', TRUE, FALSE),
    ('고등어통조림', 'FISH_AND_OTHER_SEAFOOD', 1000, 'G', 'GAE', TRUE, FALSE),
    ('갈치', 'FISH_AND_OTHER_SEAFOOD', 2800, 'G', 'MARI', FALSE, FALSE),
    ('꽁치', 'FISH_AND_OTHER_SEAFOOD', 2800, 'G', 'MARI', FALSE, FALSE),
    ('꽁치통조림', 'FISH_AND_OTHER_SEAFOOD', 900, 'G', 'GAE', TRUE, FALSE),
    ('멸치', 'FISH_AND_OTHER_SEAFOOD', 2800, 'G', 'MARI', FALSE, FALSE),
    ('국물용 멸치', 'FISH_AND_OTHER_SEAFOOD', 2000, 'G', 'CUP', FALSE, FALSE),
    ('밴댕이', 'FISH_AND_OTHER_SEAFOOD', 2800, 'G', 'MARI', FALSE, FALSE),
    ('청어', 'FISH_AND_OTHER_SEAFOOD', 2800, 'G', 'MARI', FALSE, FALSE),
    ('방어', 'FISH_AND_OTHER_SEAFOOD', 2800, 'G', 'MARI', FALSE, FALSE),
    ('부시리', 'FISH_AND_OTHER_SEAFOOD', 2800, 'G', 'MARI', FALSE, FALSE),
    ('삼치', 'FISH_AND_OTHER_SEAFOOD', 2800, 'G', 'MARI', FALSE, FALSE),
    ('전갱이', 'FISH_AND_OTHER_SEAFOOD', 2800, 'G', 'MARI', FALSE, FALSE),
    ('전어', 'FISH_AND_OTHER_SEAFOOD', 2800, 'G', 'MARI', FALSE, FALSE),
    ('준치', 'FISH_AND_OTHER_SEAFOOD', 2800, 'G', 'MARI', FALSE, FALSE),
    ('대구', 'FISH_AND_OTHER_SEAFOOD', 2800, 'G', 'MARI', FALSE, FALSE),
    ('명태', 'FISH_AND_OTHER_SEAFOOD', 2800, 'G', 'MARI', FALSE, FALSE),
    ('동태', 'FISH_AND_OTHER_SEAFOOD', 2800, 'G', 'MARI', FALSE, FALSE),
    ('황태채(북어채)', 'FISH_AND_OTHER_SEAFOOD', 3500, 'G', 'CUP', FALSE, FALSE),
    ('조기', 'FISH_AND_OTHER_SEAFOOD', 2800, 'G', 'MARI', FALSE, FALSE),
    ('굴비', 'FISH_AND_OTHER_SEAFOOD', 2800, 'G', 'MARI', FALSE, FALSE),
    ('다랑어(참치)', 'FISH_AND_OTHER_SEAFOOD', 2800, 'G', 'MARI', FALSE, FALSE),
    ('참치캔', 'FISH_AND_OTHER_SEAFOOD', 1200, 'G', 'GAE', TRUE, FALSE),
    ('연어', 'FISH_AND_OTHER_SEAFOOD', 2800, 'G', 'MARI', FALSE, FALSE),
    ('연어통조림', 'FISH_AND_OTHER_SEAFOOD', 1800, 'G', 'GAE', TRUE, FALSE),
    ('송어', 'FISH_AND_OTHER_SEAFOOD', 2800, 'G', 'MARI', FALSE, FALSE),
    ('아귀', 'FISH_AND_OTHER_SEAFOOD', 2800, 'G', 'MARI', FALSE, FALSE),
    ('메기', 'FISH_AND_OTHER_SEAFOOD', 2800, 'G', 'MARI', FALSE, FALSE),
    ('뱀장어', 'FISH_AND_OTHER_SEAFOOD', 2800, 'G', 'MARI', FALSE, FALSE),
    ('장어', 'FISH_AND_OTHER_SEAFOOD', 2800, 'G', 'MARI', FALSE, FALSE),
    ('붕장어(아나고)', 'FISH_AND_OTHER_SEAFOOD', 2800, 'G', 'MARI', FALSE, FALSE),
    ('갯장어(하모)', 'FISH_AND_OTHER_SEAFOOD', 2800, 'G', 'MARI', FALSE, FALSE),
    ('꼼장어(먹장어)', 'FISH_AND_OTHER_SEAFOOD', 2800, 'G', 'MARI', FALSE, FALSE),
    ('숭어', 'FISH_AND_OTHER_SEAFOOD', 2800, 'G', 'MARI', FALSE, FALSE),
    ('농어', 'FISH_AND_OTHER_SEAFOOD', 2800, 'G', 'MARI', FALSE, FALSE),
    ('도루묵', 'FISH_AND_OTHER_SEAFOOD', 2800, 'G', 'MARI', FALSE, FALSE),
    ('꼼치', 'FISH_AND_OTHER_SEAFOOD', 2800, 'G', 'MARI', FALSE, FALSE),
    ('양미리', 'FISH_AND_OTHER_SEAFOOD', 2800, 'G', 'MARI', FALSE, FALSE),
    ('양태', 'FISH_AND_OTHER_SEAFOOD', 2800, 'G', 'MARI', FALSE, FALSE),
    ('뱅어', 'FISH_AND_OTHER_SEAFOOD', 2800, 'G', 'MARI', FALSE, FALSE),
    ('빙어', 'FISH_AND_OTHER_SEAFOOD', 2800, 'G', 'MARI', FALSE, FALSE),
    ('까나리', 'FISH_AND_OTHER_SEAFOOD', 2800, 'G', 'MARI', FALSE, FALSE),
    ('달고기', 'FISH_AND_OTHER_SEAFOOD', 2800, 'G', 'MARI', FALSE, FALSE),
    ('가오리', 'FISH_AND_OTHER_SEAFOOD', 2800, 'G', 'MARI', FALSE, FALSE),
    ('홍어', 'FISH_AND_OTHER_SEAFOOD', 2800, 'G', 'MARI', FALSE, TRUE),
    ('상어', 'FISH_AND_OTHER_SEAFOOD', 2800, 'G', 'MARI', FALSE, FALSE),
    ('멍게', 'FISH_AND_OTHER_SEAFOOD', 2800, 'G', 'GAE', FALSE, TRUE),
    ('미더덕', 'FISH_AND_OTHER_SEAFOOD', 2800, 'G', 'GAE', FALSE, TRUE),
    ('성게', 'FISH_AND_OTHER_SEAFOOD', 2800, 'G', 'GAE', FALSE, FALSE),
    ('성게알(우니)', 'FISH_AND_OTHER_SEAFOOD', 15000, 'G', 'TBSP', TRUE, FALSE),
    ('캐비아', 'FISH_AND_OTHER_SEAFOOD', 50000, 'G', 'TBSP', TRUE, FALSE),
    ('해삼', 'FISH_AND_OTHER_SEAFOOD', 2800, 'G', 'MARI', FALSE, TRUE),
    ('군소', 'FISH_AND_OTHER_SEAFOOD', 2800, 'G', 'MARI', FALSE, TRUE),
    ('해파리', 'FISH_AND_OTHER_SEAFOOD', 2800, 'G', 'GAE', FALSE, FALSE),
    ('해면', 'FISH_AND_OTHER_SEAFOOD', 2800, 'G', 'GAE', FALSE, FALSE),
    ('갯강구', 'FISH_AND_OTHER_SEAFOOD', 2800, 'G', 'MARI', FALSE, FALSE),
    ('쏙', 'FISH_AND_OTHER_SEAFOOD', 2800, 'G', 'MARI', FALSE, FALSE),
    ('망둑어', 'FISH_AND_OTHER_SEAFOOD', 2800, 'G', 'MARI', FALSE, FALSE),
    ('베도라치', 'FISH_AND_OTHER_SEAFOOD', 2800, 'G', 'MARI', FALSE, FALSE),
    ('어묵', 'FISH_AND_OTHER_SEAFOOD', 1200, 'G', 'GAE', TRUE, FALSE),
    ('맛살(크래미)', 'FISH_AND_OTHER_SEAFOOD', 1000, 'G', 'GAE', TRUE, FALSE),
    ('날치알', 'FISH_AND_OTHER_SEAFOOD', 3500, 'G', 'TBSP', TRUE, FALSE),
    ('명란', 'FISH_AND_OTHER_SEAFOOD', 4000, 'G', 'GAE', TRUE, FALSE),
    ('명란젓', 'FISH_AND_OTHER_SEAFOOD', 4200, 'G', 'GAE', TRUE, FALSE),
    ('앤초비', 'FISH_AND_OTHER_SEAFOOD', 3000, 'G', 'GAE', TRUE, FALSE),

    -- 패류(조개류)
    ('가리비', 'SHELLFISH', 3500, 'G', 'GAE', TRUE, FALSE),
    ('굴', 'SHELLFISH', 3500, 'G', 'GAE', TRUE, TRUE),
    ('꼬막', 'SHELLFISH', 3500, 'G', 'GAE', TRUE, FALSE),
    ('명주조개', 'SHELLFISH', 3500, 'G', 'GAE', TRUE, FALSE),
    ('바지락', 'SHELLFISH', 3500, 'G', 'GAE', TRUE, FALSE),
    ('맛조개', 'SHELLFISH', 3500, 'G', 'GAE', TRUE, FALSE),
    ('새조개', 'SHELLFISH', 3500, 'G', 'GAE', TRUE, FALSE),
    ('재첩', 'SHELLFISH', 3500, 'G', 'GAE', TRUE, FALSE),
    ('전복', 'SHELLFISH', 3500, 'G', 'GAE', TRUE, FALSE),
    ('홍합', 'SHELLFISH', 3500, 'G', 'GAE', TRUE, FALSE),
    ('조개', 'SHELLFISH', 3500, 'G', 'GAE', TRUE, FALSE),
    ('다슬기', 'SHELLFISH', 3500, 'G', 'GAE', TRUE, FALSE),
    ('고둥', 'SHELLFISH', 3500, 'G', 'GAE', TRUE, FALSE),
    ('골뱅이', 'SHELLFISH', 3500, 'G', 'GAE', TRUE, FALSE),
    ('골뱅이통조림', 'SHELLFISH', 2200, 'G', 'GAE', TRUE, FALSE),

    -- 갑각류
    ('꽃게', 'CRAB', 4800, 'G', 'MARI', TRUE, FALSE),
    ('대게', 'CRAB', 4800, 'G', 'MARI', TRUE, FALSE),
    ('게', 'CRAB', 4800, 'G', 'MARI', TRUE, FALSE),
    ('새우', 'CRAB', 4800, 'G', 'MARI', TRUE, FALSE),
    ('냉동새우', 'CRAB', 2800, 'G', 'GAE', TRUE, FALSE),
    ('건새우', 'CRAB', 5500, 'G', 'CUP', TRUE, FALSE),
    ('랍스터', 'CRAB', 4800, 'G', 'MARI', TRUE, FALSE),

    -- 두족류
    ('낙지', 'CEPHALOPOD', 3000, 'G', 'MARI', TRUE, FALSE),
    ('문어', 'CEPHALOPOD', 3000, 'G', 'MARI', TRUE, FALSE),
    ('오징어', 'CEPHALOPOD', 3000, 'G', 'MARI', TRUE, FALSE),
    ('건오징어', 'CEPHALOPOD', 4000, 'G', 'GAE', TRUE, FALSE),
    ('진미채', 'CEPHALOPOD', 3200, 'G', 'CUP', TRUE, FALSE),
    ('주꾸미', 'CEPHALOPOD', 3000, 'G', 'MARI', TRUE, FALSE),
    ('한치', 'CEPHALOPOD', 3000, 'G', 'MARI', TRUE, FALSE),

    -- 난류
    ('달걀(계란)', 'EGG', 650, 'G', 'AL', TRUE, FALSE),
    ('메추리알', 'EGG', 650, 'G', 'AL', TRUE, FALSE),
    ('오리알', 'EGG', 650, 'G', 'AL', TRUE, FALSE),
    ('피단(송화단)', 'EGG', 650, 'G', 'AL', TRUE, TRUE),

    -- 양념, 조미료, 향신료 및 소스류
    ('국간장', 'SEASONING', 900, 'G', 'TBSP', TRUE, FALSE),
    ('양조간장', 'SEASONING', 900, 'G', 'TBSP', TRUE, FALSE),
    ('진간장', 'SEASONING', 900, 'G', 'TBSP', TRUE, FALSE),
    ('반간장', 'SEASONING', 900, 'G', 'TBSP', TRUE, FALSE),
    ('간장 소스', 'SEASONING', 900, 'ML', 'TBSP', TRUE, FALSE),
    ('쯔유', 'SEASONING', 1000, 'ML', 'TBSP', TRUE, FALSE),
    ('폰즈 소스', 'SEASONING', 1100, 'ML', 'TBSP', TRUE, FALSE),
    ('고추장', 'SEASONING', 900, 'G', 'TBSP', TRUE, FALSE),
    ('된장', 'SEASONING', 900, 'G', 'TBSP', TRUE, FALSE),
    ('미소된장', 'SEASONING', 900, 'G', 'TBSP', TRUE, FALSE),
    ('쌈장', 'SEASONING', 900, 'G', 'TBSP', TRUE, FALSE),
    ('두반장', 'SEASONING', 1100, 'G', 'TBSP', TRUE, FALSE),
    ('까나리액젓', 'SEASONING', 900, 'G', 'TBSP', TRUE, FALSE),
    ('멸치액젓', 'SEASONING', 900, 'G', 'TBSP', TRUE, FALSE),
    ('액젓', 'SEASONING', 900, 'G', 'TBSP', TRUE, FALSE),
    ('참치액', 'SEASONING', 900, 'G', 'TBSP', TRUE, FALSE),
    ('새우젓', 'SEASONING', 900, 'G', 'TBSP', TRUE, FALSE),
    ('맛술', 'SEASONING', 900, 'G', 'TBSP', FALSE, FALSE),
    ('식초', 'SEASONING', 900, 'G', 'TBSP', FALSE, FALSE),
    ('발사믹 식초', 'SEASONING', 1500, 'ML', 'TBSP', FALSE, FALSE),
    ('발사믹 글레이즈', 'SEASONING', 1800, 'ML', 'TBSP', FALSE, FALSE),
    ('매실청', 'SEASONING', 900, 'G', 'TBSP', FALSE, FALSE),
    ('물엿', 'SEASONING', 900, 'G', 'TBSP', FALSE, FALSE),
    ('올리고당', 'SEASONING', 900, 'G', 'TBSP', FALSE, FALSE),
    ('조청', 'SEASONING', 900, 'G', 'TBSP', FALSE, FALSE),
    ('멸치육수팩', 'SEASONING', 900, 'G', 'GAE', FALSE, FALSE),
    ('사골육수', 'SEASONING', 900, 'G', 'CUP', TRUE, FALSE),
    ('코인육수', 'SEASONING', 1200, 'G', 'GAE', FALSE, FALSE),
    ('조미료(다시다 등)', 'SEASONING', 800, 'G', 'TSP', TRUE, FALSE),
    ('소금', 'SEASONING', 300, 'G', 'TSP', FALSE, FALSE),
    ('천일염', 'SEASONING', 400, 'G', 'TSP', FALSE, FALSE),
    ('맛소금', 'SEASONING', 350, 'G', 'TSP', FALSE, FALSE),
    ('후추', 'SEASONING', 1500, 'G', 'TSP', FALSE, FALSE),
    ('고춧가루', 'SEASONING', 1800, 'G', 'TBSP', FALSE, FALSE),
    ('고추기름', 'SEASONING', 1000, 'ML', 'TBSP', FALSE, FALSE),
    ('코코아 가루', 'SEASONING', 1500, 'G', 'TBSP', FALSE, FALSE),
    ('베이킹파우더', 'SEASONING', 500, 'G', 'TSP', FALSE, FALSE),
    ('베이킹소다', 'SEASONING', 400, 'G', 'TSP', FALSE, FALSE),
    ('이스트', 'SEASONING', 1200, 'G', 'TSP', FALSE, FALSE),
    ('바닐라 익스트랙', 'SEASONING', 3000, 'G', 'TSP', FALSE, FALSE),
    ('바닐라오일', 'SEASONING', 3500, 'G', 'TSP', FALSE, FALSE),
    ('바닐라빈', 'SEASONING', 15000, 'G', 'GAE', FALSE, FALSE),
    ('계피가루(시나몬)', 'SEASONING', 1500, 'G', 'TSP', FALSE, FALSE),
    ('녹차가루', 'SEASONING', 2000, 'G', 'TSP', FALSE, FALSE),
    ('커피가루', 'SEASONING', 2500, 'G', 'TSP', FALSE, FALSE),
    ('굴소스', 'SEASONING', 1100, 'G', 'TBSP', TRUE, FALSE),
    ('케첩', 'SEASONING', 600, 'G', 'TBSP', TRUE, FALSE),
    ('마요네즈', 'SEASONING', 800, 'G', 'TBSP', TRUE, FALSE),
    ('머스타드', 'SEASONING', 900, 'G', 'TBSP', FALSE, FALSE),
    ('홀그레인 머스터드', 'SEASONING', 1200, 'G', 'TBSP', FALSE, FALSE),
    ('허니 머스터드', 'SEASONING', 1000, 'G', 'TBSP', TRUE, FALSE),
    ('갈릭 디핑 소스', 'SEASONING', 1100, 'G', 'TBSP', TRUE, FALSE),
    ('나초 치즈 소스', 'SEASONING', 1300, 'G', 'TBSP', TRUE, FALSE),
    ('돈까스소스', 'SEASONING', 900, 'G', 'TBSP', TRUE, FALSE),
    ('우스터소스', 'SEASONING', 900, 'G', 'TBSP', TRUE, FALSE),
    ('스테이크 소스', 'SEASONING', 1100, 'G', 'TBSP', TRUE, FALSE),
    ('스리라차 소스', 'SEASONING', 1200, 'G', 'TBSP', FALSE, FALSE),
    ('칠리소스', 'SEASONING', 900, 'G', 'TBSP', FALSE, FALSE),
    ('스위트 칠리소스', 'SEASONING', 900, 'G', 'TBSP', FALSE, FALSE),
    ('살사 소스', 'SEASONING', 1100, 'G', 'TBSP', FALSE, FALSE),
    ('과카몰리', 'SEASONING', 2200, 'G', 'TBSP', FALSE, FALSE),
    ('불닭 소스', 'SEASONING', 1200, 'G', 'TBSP', TRUE, FALSE),
    ('월남쌈 분짜 소스', 'SEASONING', 1100, 'ML', 'TBSP', TRUE, FALSE),
    ('카오팟 소스', 'SEASONING', 1200, 'ML', 'TBSP', TRUE, FALSE),
    ('타르타르 소스', 'SEASONING', 1000, 'G', 'TBSP', TRUE, FALSE),
    ('타르타르크림', 'SEASONING', 1500, 'G', 'TSP', FALSE, FALSE),
    ('레몬즙', 'SEASONING', 800, 'ML', 'TBSP', FALSE, FALSE),
    ('랜치 드레싱', 'SEASONING', 1200, 'ML', 'TBSP', TRUE, FALSE),
    ('시저 드레싱', 'SEASONING', 1300, 'ML', 'TBSP', TRUE, FALSE),
    ('천섬 드레싱', 'SEASONING', 1100, 'ML', 'TBSP', TRUE, FALSE),
    ('발사믹 드레싱', 'SEASONING', 1200, 'ML', 'TBSP', FALSE, FALSE),
    ('오리엔탈 드레싱', 'SEASONING', 1000, 'ML', 'TBSP', TRUE, FALSE),
    ('바질페스토', 'SEASONING', 2500, 'G', 'TBSP', TRUE, FALSE),
    ('치미추리 소스', 'SEASONING', 2000, 'G', 'TBSP', FALSE, FALSE),
    ('마라소스', 'SEASONING', 1400, 'G', 'TBSP', TRUE, FALSE),
    ('해선장', 'SEASONING', 1100, 'G', 'TBSP', TRUE, FALSE),
    ('XO 소스', 'SEASONING', 3500, 'G', 'TBSP', TRUE, FALSE),
    ('삼발 소스', 'SEASONING', 1500, 'G', 'TBSP', TRUE, FALSE),
    ('팟타이 소스', 'SEASONING', 1300, 'G', 'TBSP', TRUE, FALSE),
    ('데리야끼 소스', 'SEASONING', 1000, 'G', 'TBSP', TRUE, FALSE),
    ('토마토 파스타소스', 'SEASONING', 800, 'G', 'TBSP', TRUE, FALSE),
    ('크림 파스타소스', 'SEASONING', 1200, 'G', 'TBSP', TRUE, FALSE),
    ('피쉬소스', 'SEASONING', 1000, 'ML', 'TBSP', TRUE, FALSE),
    ('핫소스', 'SEASONING', 1000, 'G', 'TBSP', FALSE, FALSE),
    ('바비큐 소스', 'SEASONING', 950, 'G', 'TBSP', TRUE, FALSE),
    ('치킨스톡', 'SEASONING', 1200, 'G', 'TSP', TRUE, FALSE),
    ('춘장', 'SEASONING', 800, 'G', 'TBSP', TRUE, FALSE),
    ('카레가루', 'SEASONING', 1000, 'G', 'TBSP', TRUE, FALSE),
    ('와사비(고추냉이소스)', 'SEASONING', 1500, 'G', 'TSP', FALSE, TRUE),
    ('강황가루', 'SEASONING', 1500, 'G', 'TSP', FALSE, FALSE),
    ('큐민(츠란)', 'SEASONING', 1800, 'G', 'TSP', FALSE, FALSE),
    ('팔각', 'SEASONING', 2000, 'G', 'GAE', FALSE, FALSE),
    ('정향', 'SEASONING', 2200, 'G', 'TSP', FALSE, FALSE),
    ('화자오(마라향신료)', 'SEASONING', 2000, 'G', 'TSP', FALSE, TRUE),
    ('넛맥(육두구)', 'SEASONING', 2500, 'G', 'TSP', FALSE, FALSE),
    ('카다멈', 'SEASONING', 3000, 'G', 'TSP', FALSE, FALSE),
    ('코리앤더 씨드', 'SEASONING', 1800, 'G', 'TSP', FALSE, FALSE),
    ('펜넬 씨드', 'SEASONING', 1800, 'G', 'TSP', FALSE, FALSE),
    ('페누그릭', 'SEASONING', 2000, 'G', 'TSP', FALSE, FALSE),
    ('메이스', 'SEASONING', 2800, 'G', 'TSP', FALSE, FALSE),
    ('건고추', 'SEASONING', 1500, 'G', 'GAE', FALSE, FALSE),
    ('페페론치노', 'SEASONING', 2200, 'G', 'GAE', FALSE, FALSE),
    ('파프리카 가루', 'SEASONING', 1600, 'G', 'TSP', FALSE, FALSE),
    ('파슬리 가루', 'SEASONING', 1800, 'G', 'TSP', FALSE, FALSE),
    ('로즈마리', 'SEASONING', 2200, 'G', 'TSP', FALSE, FALSE),
    ('월계수 잎', 'SEASONING', 2000, 'G', 'JANG', FALSE, FALSE),
    ('케이퍼', 'SEASONING', 2500, 'G', 'TBSP', FALSE, FALSE),
    ('젤라틴', 'SEASONING', 2000, 'G', 'JANG', FALSE, FALSE),
    ('한천가루', 'SEASONING', 2200, 'G', 'TSP', FALSE, FALSE),

    -- 기타
    ('대나무', 'OTHER', 3000, 'G', 'GAE', FALSE, FALSE),
    ('달팽이', 'OTHER', 3000, 'G', 'GAE', FALSE, TRUE),
    ('인삼(홍삼)', 'OTHER', 3000, 'G', 'GAE', FALSE, FALSE),
    ('번데기통조림', 'OTHER', 800, 'G', 'GAE', FALSE, TRUE);

-- 4. 기존 DB 데이터 존재 시 값 갱신 (UPDATE)
UPDATE `food_ingredient` AS existing
    JOIN `food_ingredient_seed` AS source
    ON existing.`name` = source.`name`
SET
    existing.`type` = source.`type`,
    existing.`price_per_hundred` = source.`price_per_hundred`,
    existing.`primary_unit` = source.`primary_unit`,
    existing.`secondary_unit` = source.`secondary_unit`,
    existing.`allergy` = source.`allergy`,
    existing.`dislike` = source.`dislike`,
    existing.`updated_at` = CURRENT_TIMESTAMP;

-- 5. 존재하지 않는 신규 데이터만 추가 (INSERT)
INSERT INTO `food_ingredient` (
    `name`,
    `type`,
    `price_per_hundred`,
    `primary_unit`,
    `secondary_unit`,
    `allergy`,
    `dislike`,
    `created_at`,
    `updated_at`
)
SELECT
    source.`name`,
    source.`type`,
    source.`price_per_hundred`,
    source.`primary_unit`,
    source.`secondary_unit`,
    source.`allergy`,
    source.`dislike`,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
FROM `food_ingredient_seed` AS source
         LEFT JOIN `food_ingredient` AS existing
                   ON existing.`name` = source.`name`
WHERE existing.`name` IS NULL;

-- 6. 임시 테이블 정리 및 트랜잭션 종료
DROP TEMPORARY TABLE `food_ingredient_seed`;

COMMIT;